[project]
name = "t1-vision-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ImSmallDevil", email = "actualizh@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
t1-vision-llm = "t1_vision_llm:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
